[style.description]
underline = false
bold = false
italic = true

[style.command_name]
foreground = "green"
underline = false
bold = false
italic = false

[style.example_text]
foreground = "blue"
underline = false
bold = false
italic = false

[style.example_code]
foreground = "white"
underline = false
bold = false
italic = false

[style.example_variable]
foreground = "red"
underline = false
bold = false
italic = false

[display]
compact = true
use_pager = true

[updates]
auto_update = true
auto_update_interval_hours = 720

[directories]
