#!/bin/bash

alias tc='$EDITOR ~/.config/alacritty/alacritty.toml'

[ -f /usr/bin/batcat ] && alias cat='batcat'

if programExists eza; then
	# alias ls='eza'
	alias la="eza -laghm@ --group-directories-first --all --icons --color=always"
	alias ll="eza -lghm@ --group-directories-first --icons"
	alias l="eza --icons"
	l.() {
		if [ $# = 0 ]; then
			eza -a | grep -E '^\.'
		else
			eza -a "$@" | grep -E '^\.'
		fi
	}
  alias lld="eza -lD --no-filesize --no-permissions --octal-permissions --no-time"
else
	# alias ls='ls --color=auto'
	alias la='ls -la'
	alias ll='ls -l'
	alias l='ls'
	l.() {
		if [ $# = 0 ]; then
			command ls -A | grep -E '^\.'
		else
			command ls -A "$@" | grep -E '^\.'
		fi
	}
fi

# alias l1='ls -1'
alias lad='command ls -lad *'

# alias la="ls -AXb --group-directories-first --sort=extension"
# alias la="lsd -A --group-dirs first --classify"
# alias ldir="ls -d */"

# Alias's for multiple directory listing commands
# alias la='ls -Alh'                # show hidden files
# alias ls='command ls -aFh --color=always' # add colors and file type extensions
alias lx='ls -lXBh'      # sort by extension
alias lk='ls -lSrh'      # sort by size
alias lc='ls -lcrh'      # sort by change time
alias lu='ls -lurh'      # sort by access time
alias lr='ls -lRh'       # recursive ls
alias lt='ls -ltrh'      # sort by date
alias lm='ls -alh |more' # pipe through 'more'
alias lw='ls -xAh'       # wide listing format
# alias ll='ls -Fls'               # long listing format
alias labc='command ls -lap' #alphabetical sort
# alias lf="ls -l | egrep -v '^d'" # files only
alias ldir="command ls -l | egrep '^d'" # directories only





alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'


alias df='df -h'


alias unlock="sudo rm /var/lib/apt/lists/lock"

alias free="free -mt"

alias wget="wget -c"

alias userlist="cut -d: -f1 /etc/passwd"

alias update='sudo apt update && sudo apt upgrade -y'

alias psa="ps auxf"

alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

#grub issue 08/2022
alias install-grub-efi="sudo grub-install --target=x86_64-efi --efi-directory=/boot/efi"



alias update-fc='sudo fc-cache -fv'



alias tobash="sudo chsh $USER -s /usr/bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /usr/bin/zsh && echo 'Now log out.'"



alias tolightdm="sudo apt install lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings ; sudo systemctl enable lightdm.service -f ; echo 'Lightm is active - reboot now'"
alias tosddm="sudo apt install sddm ; sudo systemctl enable sddm.service -f ; echo 'Sddm is active - reboot now'"
alias toly="sudo apt install ly ; sudo systemctl enable ly.service -f ; echo 'Ly is active - reboot now'"
alias togdm="sudo apt install gdm ; sudo systemctl enable gdm.service -f ; echo 'Gdm is active - reboot now'"
alias tolxdm="sudo apt install lxdm ; sudo systemctl enable lxdm.service -f ; echo 'Lxdm is active - reboot now'"

alias kpi='killall picom'

alias hw="hwinfo --short"

##Virtual box
# mounting the folder Public for exchange between host and guest on virtualbox
# alias vbm="sudo mount -t vboxsf -o rw,uid=1000,gid=1000 Public /home/$USER/Public"


alias yta-aac="yt-dlp --extract-audio --audio-format aac "
alias yta-best="yt-dlp --extract-audio --audio-format best "
alias yta-flac="yt-dlp --extract-audio --audio-format flac "
alias yta-mp3="yt-dlp --extract-audio --audio-format mp3 "
alias ytv-best="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 "


alias jctl="journalctl -p 3 -xb"


alias ngrubconf='sudo $EDITOR /boot/grub/grub.cfg'
alias ngrub='sudo $EDITOR /etc/default/grub'


alias gpg-check="gpg --keyserver-options auto-key-retrieve --verify"

alias gpg-retrieve="gpg --keyserver-options auto-key-retrieve --receive-keys"


alias i3l="i3lock -i $HOME/Downloads/git_ch.png"

alias fgrep='fgrep --color=auto'

alias ga='git add'
alias gP='git pull'
alias gc='git commit -m'
alias gl7='git logg -7'
alias glg='git log'
alias glgg='git logg'
alias glgi='git logi'
alias gp='git push'
alias grep='grep --color=auto'
alias gs='clear && git status'
alias gsuo='git push --set-upstream origin'



alias ga="git add"
alias gc="git commit -m"
# alias gl="git pull --rebase --autostash"

alias gp="git push"
alias gbrr="git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format='%(refname:short)'"
alias gdh="git diff HEAD"
alias gg="lazygit"



alias kax='sudo killall Xorg'

alias l24='find . -newermt "-24 hours" -ls'

alias me='clear && exec zsh'

alias ssh='ssh -A'

alias ta='tmux attach'

alias xz='$EDITOR -c "let g:tty='\''$(tty)'\''"'

alias rbe='eval "$(rbenv init - n)"'




alias .p='cd $HOME/paperwork'
alias .d='cd $HOME/downloads'

alias .t='cd $XDG_CONFIG_HOME/alacritty'
alias .aw='cd $XDG_CONFIG_HOME/awesome'
alias .ro='cd $XDG_CONFIG_HOME/rofi'
alias .ra='cd $XDG_CONFIG_HOME/ranger'


alias ,ma='$EDITOR $ZSHDDIR/aliases'
alias ,me='$EDITOR $ZSHDDIR/exports'
alias ,mep='$EDITOR $ZSHDDIR/export.private'
alias ,mf='$EDITOR $ZSHDDIR/functions'
alias ,mzp='$EDITOR $ZSHDDIR/prompt'

alias ,mz='$EDITOR $ZDOTDIR/.zshrc'



alias kzsh='tmux kill-session -t zsh'
alias knvim='tmux kill-session -t nvim'
alias kssh='tmux kill-session -t ssh'



alias cp="cp -irv"

# alias java8="export JAVA_HOME=/usr/lib/jvm/java-8-openjdk/jre"
# alias java11="export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/"

alias mv="mv -iv"

alias ncdu="ncdu --color=dark -x"

alias plasmar="kquitapp5 plasmashell && kstart5 plasmashell"

alias pp="prettyping --nolegend"

alias rm="rm -irv"
alias rmf="rm -rf"

alias scr="scrot -cd 3 -F ~/records/screen/snap-%Y-%m-%d.png"
alias scrw="scrot -u -bcd 3 -F ~/records/screen/snap-%Y-%m-%d.png"
alias scrs="scrot -s -l width=3,color='#1688f0',mode=edge,opacity=90 -F ~/records/screen/snap-%Y-%m-%d.png"

alias sui="systemctl --user status"
alias sud="systemctl --user disable"
alias sue="systemctl --user enable"
alias suE="systemctl --user edit"
alias sur="systemctl --user restart"
alias suR="systemctl --user reload"
alias sus="systemctl --user start"
alias sut="systemctl --user stop"
alias ssi="systemctl status"
alias ssd="sudo systemctl disable"
alias sse="sudo systemctl enable"
alias ssE="sudo systemctl edit"
alias ssr="sudo systemctl restart"
alias ssR="sudo systemctl reload"
alias sss="sudo systemctl start"
alias sst="sudo systemctl stop"

# alias tmux="tmux -u"
alias tmuxm="tmux new-session \; split-window -h \; split-window -v \; attach"

alias todo='nvim +"Telekasten goto_today"'

# Causes Issues
# if [ -f "/usr/bin/kdeconnect-cli" ]; then
# 	alias send="kdeconnect-cli -d "$(kdeconnect-cli -a --id-only)" --share"
# fi

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# alias to show the date
alias da='date "+%Y-%m-%d %A %T %Z"'

alias mkdir='mkdir -p'

alias ps='ps auxf'
alias p="ps aux | grep "
alias topcpu="/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10"

alias ping='ping -c 10'
alias openports='netstat -nape --inet'

alias less='less -R'

alias mx='chmod a+x'
alias 000='chmod -R 000'
alias 644='chmod -R 644'
alias 666='chmod -R 666'
alias 755='chmod -R 755'
alias 777='chmod -R 777'

alias h="history"

alias f="find . | grep "

alias rebootsafe='sudo shutdown -r now'
alias rebootforce='sudo shutdown -r -n now'

alias files="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'"
alias e='nvim $(files)'

alias fd="fd -H"
alias fdir="find . -type d -name"
alias ffil="find . -type f -name"

alias diskspace="du -S | sort -n -r | less"
alias folders='du -h --max-depth=1'
alias folderssort='find . -maxdepth 1 -type d -print0 | xargs -0 du -sk | sort -rn'
alias tree='tree -CAhF --dirsfirst'
alias treed='tree -CAFd'

# Alias's for archives
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

# Show all logs in /var/log
alias logs="sudo find /var/log -type f -exec file {} \; | grep 'text' | cut -d' ' -f1 | sed -e's/:$//g' | grep -v '[0-9]$' | xargs tail -f"

# alias rcp='rsync -v --progress'
# alias rmv='rsync -v --progress --remove-source-files'
# alias chmod="chmod -c"
# alias chown="chown -c"

if command -v diff-so-fancy >/dev/null 2>&1; then
	function diff() {
		command diff -u "$@" | diff-so-fancy
	}
elif command -v colordiff >/dev/null 2>&1; then
	diff_ex=colordiff
	function diff() {
		$diff_ex -Nuar "$@" | command less -R
	}
else
	alias diff="diff -Nuar --color=auto"
fi

alias root="sudo -E -s"

alias sp="source $ZSHDDIR/export.private"

alias sam="sudo apt-manage modify"
alias as="apt search"
alias aS="apt show"
alias ac="apt-cache search"
alias sai="sudo apt install"
alias sar="sudo apt remove"
alias sap="sudo apt purge"

alias d="docker"
alias dc="docker compose"
alias di="docker image"
alias dn="docker network"
alias v="$EDITOR"
