#!/bin/bash
# {{{ Other program keep updating my bashrc.  Oh well!

[[ -f /usr/share/fzf/completion.bash ]] &&
	. /usr/share/fzf/completion.bash

[[ -f /usr/share/fzf/key-bindings.bash ]] &&
	. /usr/share/fzf/key-bindings.bash

[[ -f ~/.fzf.bash ]] &&
	. ~/.fzf.bash

# [[ -f $HOME/.config/lua-language-server/3rd/luamake/luamake ]] && \
#       alias luamake=$HOME/.config/lua-language-server/3rd/luamake/luamake

# [[ -f $HOME/lib/azure-cli/az.completion ]] && \
#     . $HOME/lib/azure-cli/az.completion

# [[ -f $HOME/.cargo/env ]] && \
#    .  $HOME/.cargo/env

# -------------------------------------------------------------------------- }}}
